#!/bin/bash


#conda activate e2c 
#python  setup.py  install
DIR=/global/cfs/cdirs/e3sm/xie7/ccmi/ccmi_cmor/e3sm_to_cmip/xjb_use/batch/
VAR1=(PSL  PS  PRECT  PRECC  FLUT  TREFHT  U10  TROP_P  TROP_T  T  U  V  OMEGA  Z3)
VAR2=(psl  ps  pr     prc    rlut  tas     uas  ptp     tatp    ta ua va wap    zg)
#
#for i in {0..13..1}; do
for i in {9..9..1}; do
FILENAME=v3.ccmi.PD_INT_custom30_${VAR1[i]}.sh
cp $DIR/sub  $FILENAME
echo ${VAR1[i]}
sed -i "/var1=/c  var1=${VAR1[i]}"       $FILENAME
sed -i "/var2=/c  var2=${VAR2[i]}_mon"   $FILENAME
./$FILENAME >& output_${VAR1[i]}    &
done




exit
