#!/bin/bash


#conda activate e2c 
#python  setup.py  install
SUB=sub12
echo batch_table5_sur  $SUB
case=v3.ccmi.FD_NINT_4xCO2_custom30_mem3
DIR=/global/cfs/cdirs/e3sm/xie7/ccmi/ccmi_cmor/e3sm_to_cmip/xjb_use/batch/
VAR1=(AODABS  TOZ)
VAR2=(aod     toz)
scale=mon
years=30
#
for i in {0..1..1}; do
FILENAME=$case\_${VAR1[i]}\_mon.sh
cp $DIR/$SUB  $FILENAME
echo ${VAR1[i]}
sed -i "/input=/c input=/global/cfs/cdirs/e3sm/xie7/ccmi/$case/output/${VAR1[i]}/post/atm/180x360_aave/ts/monthly/"$years"yr/" $FILENAME
sed -i "/var1=/c  var1=${VAR1[i]}"       $FILENAME
sed -i "/var2=/c  var2=${VAR2[i]}_mon"   $FILENAME
./$FILENAME >& output_${VAR1[i]}_mon    
#
done




