#!/bin/bash
case=v3.ccmi.PD_INT_custom30
var1=PRECT
var2=pr_mon
year=90yr
scale=monthly
output=/global/cfs/cdirs/e3sm/xie7/ccmi_output/

e3sm_to_cmip  -i /global/cfs/cdirs/e3sm/xie7/ccmi/$case/output/$var1/post/atm/180x360_aave/ts/$scale/$year/  -o  $output  -v  $var2  -t   /global/cfs/cdirs/e3sm/xie7/ccmi/ccmi_cmor/e3sm_to_cmip/e3sm_to_cmip/resources/   -u   /global/cfs/cdirs/e3sm/xie7/ccmi/ccmi_cmor/e3sm_to_cmip/e3sm_to_cmip/resources/ccmi_template.json  -H  /global/cfs/cdirs/e3sm/xie7/ccmi/ccmi_cmor/e3sm_to_cmip/e3sm_to_cmip/cmor_handlers/

exit
