# %%
from e3sm_to_cmip.runner import E3SMtoCMIP

# -----------------
# SETUP
# -----------------
# historical
exp = "historical"
# expshort=hist-nat
# exp=hist-all-xGHG-xaer
caseid = "v2.LR.${exp}_0101"
start = 1850
end = 1850
ypf = 1

# -----------------
# PATHS
# -----------------
e2c_path = "/p/user_pub/e3sm/zhang40/e3sm_to_cmip_data/"
model_data = f"{e2c_path}/model-output"

result_dir = "/p/user_pub/e3sm/e3sm_to_cmip/test-cases/115-branch"
# NOTE: result_dir2 is only for the output data to be saved in local directory
# for easy debugging and to not overwrite any existing files under `result_dir`
# generated by the complete `115-end-to-end-script.sh`.
# result_dir2 = "qa/115-branch"

rgr_dir = f"{result_dir}/rgr"
rgr_dir_vert = f"{result_dir}/rgr_vert"
rgr_dir_vert_plev = f"{result_dir}/rgr_vert_plev"
native_dir = f"{result_dir}/native"

map_file = f"{e2c_path}/maps/map_ne30pg2_to_cmip6_180x360_aave.20200201.nc"
tables_path = f"{e2c_path}/cmor/cmip6-cmor-tables/Tables/"
metadata_path = f"{e2c_path}/user_metadata.json"


"""

1. Debug missing variables (cl, clw, cli)
  - Files generate but time is missing causing errors when opening dataset
  - Has incorrect file name extension with dev branch
  - Cause: zfactor with ips, name "ps2" incorrect (only pfull), should be "ps"
  - Fix: Add conditional to rename to "ps2" if var name is "pfull"
2. orog.py, areacella.py, sftlf.py
  - Issue: incorrect number of positional arguments in `_run_parallel.py` -- FIXED
3. tas, huss, tasmax, pr
  - Issue: unable ot start new threads due to too many threads (set -n 1) -- FIXED
4. phalf not working -- conditional with z factors incorrect -> standard_sigma_hybrih_half -- FIXED
5. Debug variables that have mismatching nans  -- IN PROGRESS
  a. Confirmed regridded datasets are the same
    - /p/user_pub/e3sm/e3sm_to_cmip/test-cases/master/rgr/AODABS_185001_185012.nc
    - /p/user_pub/e3sm/e3sm_to_cmip/test-cases/115-branch-np-na/rgr/AODABS_185001_185012.nc
  b. Tested with changing fill value, does nothing
  c. Found that the history attribute of some variables differed with :
     - "2023-11-02T21:06:08Z altered by CMOR: Reordered dimensions, original order: lat lon time."]
     - I found out that the order of the CMOR ids in the mapping table did not align with the original code, where "time" and "lev" should be first to align with the CMOR tables
6. Debug mrfso and mrso vertical sum formulas producing incorrect shapes -- FIXED
    - Cause: Due to `xr.sum` and `np.sum` behavior with xr.DataArray, which replaces np.nan values with 0's.
    - Solution: Use `np.sum` with the underlying np.ndarray and reconstruct the resulting xr.DataArray.
7. Fix phalf and pfull large differences -- IN PROGRESS

"""
# %%
raw_var_list = "ICEFRAC,OCNFRAC,LANDFRAC,PHIS,hyam,hybm,hyai,hybi,TREFHT,TS,PSL,PS,U10,QREFHT,PRECC,PRECL,PRECSC,PRECSL,QFLX,TAUX,TAUY,LHFLX,CLDTOT,FLDS,FLNS,FSDS,FSNS,SHFLX,CLOUD,CLDICE,TGCLDIWP,CLDLIQ,TGCLDCWP,TMQ,FLNSC,FSNTOA,FSNT,FLNT,FLUTC,FSDSC,SOLIN,FSNSC,FSUTOA,FSUTOAC,AODABS,AODVIS,AREL,TREFMNAV,TREFMXAV,FISCCP1_COSP,CLDTOT_ISCCP,MEANCLDALB_ISCCP,MEANPTOP_ISCCP,CLD_CAL,CLDTOT_CAL,CLDLOW_CAL,CLDMED_CAL,CLDHGH_CAL"

cmip_var_list = "pfull"


args2 = [
    "-i",
    rgr_dir,
    "-o",
    result_dir,
    "-v",
    cmip_var_list,
    "-t",
    tables_path,
    "-u",
    metadata_path,
    "--serial",
]

run2 = E3SMtoCMIP(args2)
run2.run()

# %%
