package:
  name: e3sm_to_cmip
  version: {{ environ['VERSION'] }}

source:
  path: ..
  git_url: git://github.com/E3SM-Project/e3sm_to_cmip.git
  git_tag: {{ environ['TAG'] }}

build:
  script: python setup.py install
  string: {{ environ['BUILD_NAME'] }}

about:
  home: https://github.com/E3SM-Project/e3sm_to_cmip
  summary: |
    Transform E3SM model data output into cmip6 compatable data using the
    Climate Model Output Rewritter.

requirements:
  host:
    - python
    - pip
    - setuptools

run:
    - python
    - nco
    - cmor >=3.5.0
    - cdutil
    - cdms2 >=3.1
    - tqdm
    - pathos
    - pyyaml
    - xarray
    - netcdf4
    - dask
    - scipy

