#!/bin/bash
case=v3.ccmi.PD_INT_custom30
vars=PRECT
year=90yr
scale=monthly

e3sm_to_cmip  -i /global/cfs/cdirs/e3sm/xie7/ccmi/$case/output/$vars/post/atm/180x360_aave/ts/$scale/$year/  -o  /global/cfs/cdirs/e3sm/xie7/ccmi_output/   -v  prc_mon  -t   /global/cfs/cdirs/e3sm/xie7/ccmi/ccmi_cmor/e3sm_to_cmip/e3sm_to_cmip/resources/   -u   /global/cfs/cdirs/e3sm/xie7/ccmi/ccmi_cmor/e3sm_to_cmip/e3sm_to_cmip/resources/ccmi_template.json  -H  /global/cfs/cdirs/e3sm/xie7/ccmi/ccmi_cmor/e3sm_to_cmip/e3sm_to_cmip/cmor_handlers/

exit
