name: CI/CD Build Workflow

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

  workflow_dispatch:

env:
  CANCEL_OTHERS: true
  PATHS_IGNORE: '["**/README.md", "**/docs/**", "**/examples/**", "**/misc/**", "**/.vscode/**"]'

jobs:
  build:
    name: Build (Python ${{ matrix.python-version }})
    runs-on: "ubuntu-latest"
    timeout-minutes: 10
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: ${{ env.CANCEL_OTHERS }}
          paths_ignore: ${{ env.PATHS_IGNORE }}
          do_not_skip: '["push", "workflow_dispatch"]'

      - if: ${{ steps.skip_check.outputs.should_skip != 'true' }}
        uses: actions/checkout@v3

      - if: ${{ steps.skip_check.outputs.should_skip != 'true' }}
        name: Set up Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: "e3sm_to_cmip_ci"
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
          mamba-version: "*"
          environment-file: conda-env/ci.yml
          channel-priority: strict
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

      # Refresh the cache every 24 hours to avoid inconsistencies of package versions
      # between the CI pipeline and local installations.
      - if: ${{ steps.skip_check.outputs.should_skip == 'false' }}
        id: get-date
        name: Get Date
        run: echo "today=$(/bin/date -u '+%Y%m%d')" >> $GITHUB_OUTPUT
        shell: bash

      - if: ${{ steps.skip_check.outputs.should_skip == 'false' }}
        id: cache
        name: Cache Conda env
        uses: actions/cache@v3
        with:
            path: ${{ env.CONDA }}/envs
            key:
                conda-${{ runner.os }}-${{ runner.arch }}-${{ matrix.python-version }}-${{
                steps.get-date.outputs.today }}-${{hashFiles('conda-env/ci.yml') }}-${{ env.CACHE_NUMBER}}
        env:
            # Increase this value to reset cache if conda-env/ci.yml has not changed in the workflow
            CACHE_NUMBER: 0

      - if: |
            steps.skip_check.outputs.should_skip == 'false' &&
            steps.cache.outputs.cache-hit == 'false'
        name: Update environment
        run: |
            mamba env update -n e3sm_to_cmip_ci -f conda-env/ci.yml
            # Make sure the Python version in the env matches the current matrix version.
            mamba install -c conda-forge python=${{ matrix.python-version }}

      - if: ${{ steps.skip_check.outputs.should_skip == 'false' }}
        name: Install e3sm_to_cmip
        # Source: https://github.com/conda/conda-build/issues/4251#issuecomment-1053460542
        run: |
            python -m pip install --no-build-isolation --no-deps -e .

      - if: ${{ steps.skip_check.outputs.should_skip != 'true' }}
        name: Check conda env
        run: |
          mamba list
          mamba info

      - if: ${{ steps.skip_check.outputs.should_skip != 'true' }}
        name: Run Tests
        run: pytest

      - if: ${{ steps.skip_check.outputs.should_skip != 'true' }}
        name: Upload Coverage Report
        uses: codecov/codecov-action@v3
        with:
          file: "tests_coverage_reports/coverage.xml"
          fail_ci_if_error: true
