#!/bin/bash


#conda activate e2c 
#python  setup.py  install
CASE=v3.ccmi.PD_INT_custom30
DIR=/global/cfs/cdirs/e3sm/xie7/ccmi/ccmi_cmor/e3sm_to_cmip/xjb_use/batch/
VAR1=(PSL  PS  PRECT  PRECC  FLUT  TREFHT  U10  TROP_P  TROP_T)
VAR2=(psl  ps  pr     prc    rlut  tas     uas  ptp     tatp  )
scale=mon
#
#for i in {0..7..1}; do
for i in {4..4..1}; do
FILENAME=$CASE\_${VAR1[i]}\_mon.sh
cp $DIR/sub  $FILENAME
echo ${VAR1[i]}
sed -i "/input=/c input=/global/cfs/cdirs/e3sm/xie7/ccmi/$CASE/output/${VAR1[i]}/post/atm/180x360_aave/ts/monthly/90yr/" $FILENAME
sed -i "/var1=/c  var1=${VAR1[i]}"       $FILENAME
sed -i "/var2=/c  var2=${VAR2[i]}_mon"   $FILENAME
#./$FILENAME >& output_${VAR1[i]}    &
#
FILENAME=$CASE\_${VAR1[i]}\_day.sh
cp $DIR/sub  $FILENAME
echo ${VAR1[i]}
sed -i "/input=/c input=/global/cfs/cdirs/e3sm/xie7/ccmi/$CASE/output/${VAR1[i]}/post/atm/180x360_aave/ts/daily/30yr/" $FILENAME
sed -i "/var1=/c  var1=${VAR1[i]}"       $FILENAME
sed -i "/var2=/c  var2=${VAR2[i]}_day"   $FILENAME
./$FILENAME >& output_${VAR1[i]}    &


done




exit
