#!/bin/bash


#conda activate e2c 
#python  setup.py  install
DIR=/global/cfs/cdirs/e3sm/xie7/ccmi/ccmi_cmor/e3sm_to_cmip/xjb_use/batch/
VAR1=(VT  UV  UW)
VAR2=(vt  uv  uomega)
#
case=v3.ccmi.PD_INT_custom30
scale=6hrPt
scale1=$scale
scale2=$scale\Z
#
for i in {0..7..1}; do
#for i in {0..0..1}; do
#
FILENAME=$case\_${VAR1[i]}_$scale2.sh
cp $DIR/sub  $FILENAME
sed -i "/var1=/c  var1=${VAR1[i]}"       $FILENAME
sed -i "/var2=/c  var2=${VAR2[i]}\_$scale2"  $FILENAME
#sed -i "/input=/c  input=/global/cfs/cdirs/e3sm/xie7/ccmi_output/proc_med/output/$case/hourly/2D/"  $FILENAME
sed -i "/input=/c   input=/global/cfs/cdirs/e3sm/xie7/ccmi_output/proc_med/output/v3.ccmi.PD_INT_custom30/tem/hourly/${VAR1[i]}/"      $FILENAME
./$FILENAME >& output_$scale2\_${VAR1[i]}    #&
done




exit
