#!/bin/bash


#conda activate e2c 
#python  setup.py  install
SUB=sub
echo batch_table3_lev $SUB
DIR=/global/cfs/cdirs/e3sm/xie7/ccmi/ccmi_cmor/e3sm_to_cmip/xjb_use/batch/
VAR1=(TTEND_TOT  QRL  QRLC  QRS  QRSC  UTEND_CLUBB  UTGWORO  UTGWSPEC  VTEND_CLUBB  VTGWORO  VTGWSPEC  TOT_CLD_VISTAU  CONCLD  CLOUD)
VAR2=(zmtnt  tntrl  tntrlcs  tntrs  tntrscs  utendmp  utendogw  utendnogw  vtendmp  vtendogw  vtendnogw  cod cltc  clt)
#
case=v3.ccmi.PD_INT_custom30
scale=mon
scale1=monZ
scale2=dayZ
scale3=mon
#
#if [[ 1 -eq 2 ]]; then
#
for i in {0..10..1}; do
FILENAME=$case\_${VAR1[i]}_$scale1.sh
cp $DIR/$SUB  $FILENAME
echo ${VAR1[i]} $i monZ
sed -i "/var1=/c  var1=${VAR1[i]}"       $FILENAME
sed -i "/var2=/c  var2=${VAR2[i]}\_$scale1"   $FILENAME
sed -i "/input=/c input=/global/cfs/cdirs/e3sm/xie7/ccmi_output/proc_med/output/$case/monthly/2D/"   $FILENAME
./$FILENAME >& output_$scale1\_${VAR1[i]}    #&
done
#
#fi
##
##
for i in {0..10..1}; do
FILENAME=$case\_${VAR1[i]}_$scale2.sh
cp $DIR/$SUB  $FILENAME
echo ${VAR1[i]} $i dayZ
sed -i "/var1=/c  var1=${VAR1[i]}"       $FILENAME
sed -i "/var2=/c  var2=${VAR2[i]}\_$scale2"  $FILENAME
sed -i "/input=/c input=/global/cfs/cdirs/e3sm/xie7/ccmi_output/proc_med/output/$case/daily/2D/"   $FILENAME
./$FILENAME >& output_$scale2\_${VAR1[i]}    #&
done
#
#exit
#
for i in {11..13..1}; do
FILENAME=$case\_${VAR1[i]}_$scale3.sh
cp $DIR/sub  $FILENAME
echo ${VAR1[i]} $i mon
sed -i "/var1=/c  var1=${VAR1[i]}"       $FILENAME
sed -i "/var2=/c  var2=${VAR2[i]}\_$scale3"   $FILENAME
sed -i "/input=/c input=/global/cfs/cdirs/e3sm/xie7/ccmi_output/proc_med/output/$case/monthly/3D/"   $FILENAME
./$FILENAME >& output_$scale3\_${VAR1[i]}    #&
done



